# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
inhibit_all_warnings!

target 'Aftercare' do
  # Pods for Dentacare
  
  pod 'Alamofire'
  pod 'CodableAlamofire'
  pod 'AlamofireImage'
  
  #Simplify Facebook SignIn
  pod 'FacebookCore'
  pod 'Firebase/Messaging'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  #Simplify Twitter SignIn
  pod 'TwitterKit'
  
  #Simplify Google SignIn trough Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  
  #Persistence helper
  pod 'Disk'
  
  #Use google auto complete view controller for choosing valid country/city
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  
  #QRCode
  pod 'QRCodeReader.swift', '8.2.0'
  
  #Fabric/Crashlytics
  pod 'Fabric', '1.7.7'
  pod 'Crashlytics', '3.10.2'
  
  #Sound Helper
  pod 'SwiftySound', '1.0.0'
  
end
