# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

inhibit_all_warnings!

target 'Aftercare' do
  # Pods for Dentacare
  
  pod 'Alamofire', '~> 4.5'
  pod 'CodableAlamofire'
  pod 'AlamofireImage', '~> 3.3'
  
  #Simplify Facebook SignIn
  pod 'FacebookCore'
  pod 'Firebase/Messaging'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  #Simplify Twitter SignIn
  pod 'TwitterKit'
  #Simplify Google SignIn trough Firebase
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  
  #Persistence helper
  pod 'Disk', '~> 0.3.1'
  
  #Spotlight Tutorials
  pod 'AwesomeSpotlightView'
  
  #Use google auto complete view controller for choosing valid country/city
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  
  #QRCode
  pod 'QRCodeReader.swift', '~> 8.0.3'
  
  #Fabric/Crashlytics
  pod 'Fabric'
  pod 'Crashlytics'
  
  #Sound Helper
  pod 'SwiftySound'
  
end
